# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme             : "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Steps"
title_separator          : "-"
name                     : &name "FC"
description              : &description "Stepping stones"
url                      : "https://jekyll.casier.nl"# the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "frca1958/site_jekyll"
teaser                   : "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : #"staticman_v2" # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman_v2", "staticman" "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : # "New comment"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "_data/comments/{options.slug}"
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
reCaptcha:                #For domain casier.nl
  siteKey                : "6Lejpl0UAAAAAFO94LjPmc5Xz7l8F2_UDmCRL5lF"
  secret                 : "6Lejpl0UAAAAAOtXx5UpVM-Jd5o7frkCU2J2pZ0s"

atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : #algolia # lunr (default), algolia
# algolia:
#   application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
#   index_name             : minimal_mistakes # YOUR_INDEX_NAME
#   search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : true # true (default), false
#   files_to_exclude:
#     - _posts/2017-11-28-post-exclude-search.md

# SEO Related
google_site_verification : #"UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y" # Replace this with your ID, or delete
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : #&twitter "fc"
facebook:
  username               : #&facebook "fc"
  app_id                 :
  publisher              :
og_image                 : #"/assets/images/fc-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    #- "https://twitter.com/fc"
    #- "https://facebook.com/fc"

# Analytics
analytics:
  provider               : #"google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : #"UA-2011187-3" # Replace this with your ID, or delete
    anonymize_ip         : true


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/fc_avatar.png"
  bio              : "Thats me."
  location         : "Brussels"
  email            :
  uri              : #"https://mademistakes.com"
  home             : #"https://mademistakes.com"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : #*facebook
  foursquare       :
  github           : "frca1958"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : #"mmistakes"
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : *twitter
  vine             :
  weibo            :
  xing             :
  youtube          :


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - tmp
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Structure of the docs
#   /c/_posts/          --> blogs
#   /c/_drafs/          --> drafts
#   /c/<collection>/    --> collection articles
#
#
# Structure of the generated site
#   /c/posts/<postlink>         --> blogs 
#   /c/<collection>/<titles>    --> collections
#



# BLOGS  
timezone: "Europe/Brussels"
paginate: 5 # amount of posts to show
paginate_path: "/c/posts/page:num/"



# Collections
collections_dir: c
collections:
  posts:
    output: true
    permalink: /c/posts/:year/:month/:day/:title/
  howto:
    output: true
    permalink: /c/:collection/:path/


# Defaults
defaults:
  # _posts: everything that is not in a special folder
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      #read_time: true
      #comments: true
      related: true
      classes: wide
      sidebar:
        nav: "posts"
      
  # _pages
  - scope:
      path: ""
      type: pages
      #must be defined in the page. permalink: :path
    values:
      layout: single
  # _howto
  - scope:
      path: ""
      type: howto
    values:
      layout: single
      sidebar:
        nav: "howto"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style




# # Plugins (previously gems:)
# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jemoji

# # mimic GitHub Pages with --safe
# whitelist:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jekyll-feed
#   - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /c/posts/byCat
#  path: /categories/
tag_archive:
  type: liquid
  path: /c/posts/byTag
#  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development



github: [metadata]