# Site
# ----
title: FC Jekyll Site
email: fc@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My first steps with jekyll.
  I guess this is not worth being searched.
baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "https://blog.casier.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  frca1958


# Theme and plugins
# -----------------

theme: minima   #jekyll-theme-cayman #remote_theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 5




# Build settings

markdown: kramdown



#  DEFAULTS for FRONTMATTER 
#  ------------------------

defaults:
  -
    scope:
      path: "posts" # an empty string here means all files in the project
    values:
      layout: "post"





#  GLOBAL CONFIG
#  -------------
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
