source "https://rubygems.org"

# After changes
#   bundle install
#   bundle exec jekyll serve -H:0.0.0.0
#

#gem "jekyll", "~> 3.7.3"
gem "github-pages", group: :jekyll_plugins

gem "minima", "~> 2.0"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end


#for windows
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?

